name: 'Terraform init'

inputs:
  environment:
    description: 'terraform environment'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install tfnotify
      run: |
        wget https://github.com/mercari/tfnotify/releases/download/v0.7.0/tfnotify_linux_amd64.tar.gz
        tar xvzf tfnotify_linux_amd64.tar.gz
        chmod 777 tfnotify
      shell: bash

    - name: Terraform init
      run: make terraform-init ENVIRONMENT=${{ inputs.environment }}
      shell: bash

    - name: Terraform Format
      run: make terraform-fmt ENVIRONMENT=${{ inputs.environment }} | ./tfnotify fmt
      shell: bash

    - name: Terraform plan
      run: make terraform-plan ENVIRONMENT=${{ inputs.environment }} | ./tfnotify plan
      shell: bash
