name: Terraform apply

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/action/
        with:
          environment: template
      - name: Terraform apply
        run: make terraform-apply ENVIRONMENT=template
